# Use a base image with Jupyter pre-installed
FROM jupyter/scipy-notebook

# Set working directory
WORKDIR /app

# Expose the Jupyter port
EXPOSE 8888

# Command to start Jupyter notebook in the /app directory
CMD ["start-notebook.sh", "--ip=0.0.0.0", "--port=8888", "--NotebookApp.notebook_dir=/app"]
