# Use a base Python image
FROM python:3

# Set working directory
WORKDIR /app

# Copy necessary files into the container
COPY requirements.txt /app

# Upgrade pip and setuptools, then install dependencies
RUN pip install --upgrade pip setuptools && pip install -r requirements.txt -t /libraries
